[features]
seeds = false
skip-lint = false
[programs.localnet]
oracle_smart_contract = "DNg1Qxv3r1CyN7NMmxh67kMjc7q6Bv5VHtoXhKnCL8bY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
